---
- name: Create multiple VMs on OpenStack and auto-register to Rancher
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    rancher_url: "https://k8smanager.comtegra.pl"
    rancher_token: "token-p8htt:zmjjkpcfzb5gdrmq5djfsm4wrzszk9kb8fbqjpng9pvkmqm4fz762w"
    cluster_name: "{{ cluster_name }}"

    vm_count: "{{ vm_count | int }}"
    node_roles: "{{ node_roles }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_name_prefix: "{{ vm_name_prefix }}"

    vm_image: "4e04bf46-b48f-4bd2-a15a-efdd3a666d43"
    vm_keypair: "k8s"

    os_auth_url: "https://10.1.71.88:5000/v3"
    os_project_name: "admin"
    os_project_id: "e9f88faebaa44e3893fd26f9d41f9927"
    os_project_domain_id: "9021632abac74b018ee13e95c5e81bea"
    os_username: "admin"
    os_user_domain_name: "admin_domain"
    os_password: "Yaoki0kohghoQu9y"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:

    ###########################################################################
    # VALIDATION
    ###########################################################################
    - name: Validate vm_count
      fail:
        msg: "vm_count must be positive"
      when: vm_count < 1

    - name: Convert comma-separated roles into list
      set_fact:
        parsed_roles: "{{ node_roles.split(',') }}"

    - name: Ensure role count matches VM count
      assert:
        that:
          - parsed_roles | length == vm_count

    - name: Generate VM numbers
      set_fact:
        vm_list: "{{ query('sequence','start=1 end=' + vm_count|string) }}"

    - name: Build VM → role map
      set_fact:
        vm_role_map: "{{ vm_list | zip(parsed_roles) | list }}"

    - debug:
        msg: "VM {{ vm_name_prefix }}-{{ item.0 }} will be {{ item.1 }}"
      loop: "{{ vm_role_map }}"

    ###########################################################################
    # RANCHER API CALLS
    ###########################################################################

    - name: Get Rancher cluster info
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_info

    - name: Fail if cluster not found
      fail:
        msg: "Cluster {{ cluster_name }} not found in Rancher!"
      when: cluster_info.json.data | length == 0

    - name: Set Rancher cluster ID
      set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Debug Rancher cluster ID
      debug:
        msg: "Cluster ID: {{ cluster_id }}"

    - name: Check for existing registration tokens
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: existing_tokens

    - name: Create Rancher registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
        status_code: 201,200
      register: token_create
      when: existing_tokens.json.data | length == 0

    - name: Wait for nodeCommand to be ready
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: reg_info
      until: reg_info.json.data[0].nodeCommand is defined and reg_info.json.data[0].nodeCommand != ""
      retries: 20
      delay: 5

    - name: Store node command and token
      set_fact:
        node_command: "{{ reg_info.json.data[0].nodeCommand }}"
        registration_token: "{{ reg_info.json.data[0].token }}"

    - debug:
        msg: "Node command ready. Token prefix: {{ registration_token[:10] }}..."

    ###########################################################################
    # CLOUD-INIT GENERATION
    ###########################################################################

    - name: Create cloud-init files
      copy:
        dest: "/tmp/cloud-init-{{ vm_name_prefix }}-{{ item.0 }}.yml"
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl
            - docker.io
            - jq

          write_files:
            - path: /etc/hosts
              content: |
                10.1.77.17 k8smanager.comtegra.pl

          runcmd:
            - systemctl enable docker
            - systemctl start docker
            - sleep 5
            - curl -k -I {{ rancher_url }}

            - |
              BASE="{{ node_command }}"
              BASE=$(echo "$BASE" | sed 's/curl /curl -k /g')
              FINAL="$BASE"
              {% if 'etcd' in item.1 %}FINAL="$FINAL --etcd"{% endif %}
              {% if 'controlplane' in item.1 %}FINAL="$FINAL --controlplane"{% endif %}
              {% if 'worker' in item.1 %}FINAL="$FINAL --worker"{% endif %}
              FINAL="$FINAL --node-name {{ vm_name_prefix }}-{{ item.0 }}"
              
              echo "$FINAL" > /tmp/run.sh
              chmod +x /tmp/run.sh
              bash /tmp/run.sh

      loop: "{{ vm_role_map }}"

    ###########################################################################
    # CREATE VMs
    ###########################################################################

    - name: Create VMs on OpenStack
      openstack.cloud.server:
        state: present
        name: "{{ vm_name_prefix }}-{{ item.0 }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ lookup('file', '/tmp/cloud-init-' + vm_name_prefix + '-' + item.0|string + '.yml') }}"
        auto_ip: yes
        wait: yes
        timeout: 600
      register: new_vms
      loop: "{{ vm_role_map }}"

    ###########################################################################
    # WAIT FOR CLUSTER ACTIVATION
    ###########################################################################

    - name: Wait for nodes to register in Rancher
      uri:
        url: "{{ rancher_url }}/v3/nodes?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: rancher_nodes
      until: rancher_nodes.json.data | length >= vm_count
      retries: 30
      delay: 10

    - debug:
        msg: "Detected {{ rancher_nodes.json.data | length }} registered nodes."

    - name: Wait for cluster state ACTIVE
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_state
      until: cluster_state.json.state == "active"
      retries: 50
      delay: 10

    - debug:
        msg: "🎉 Cluster {{ cluster_name }} is ACTIVE!"

    ###########################################################################
    # CLEANUP
    ###########################################################################

    - name: Remove cloud-init temp files
      file:
        path: "/tmp/cloud-init-{{ vm_name_prefix }}-{{ item.0 }}.yml"
        state: absent
      loop: "{{ vm_role_map }}"
