---
- name: Create multiple VMs on OpenStack and auto-register to Rancher
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    rancher_url: "https://k8smanager.comtegra.pl"
    rancher_token: "token-p8htt:zmjjkpcfzb5gdrmq5djfsm4wrzszk9kb8fbqjpng9pvkmqm4fz762w"
    cluster_name: "{{ cluster_name }}"

    vm_count: "{{ vm_count | int }}"
    node_roles: "{{ node_roles }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_name_prefix: "{{ vm_name_prefix }}"

    vm_image: "4e04bf46-b48f-4bd2-a15a-efdd3a666d43"
    vm_keypair: "k8s"

    os_auth_url: "https://10.1.71.88:5000/v3"
    os_project_name: "admin"
    os_project_id: "e9f88faebaa44e3893fd26f9d41f9927"
    os_project_domain_id: "9021632abac74b018ee13e95c5e81bea"
    os_username: "admin"
    os_user_domain_name: "admin_domain"
    os_password: "Yaoki0kohghoQu9y"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:

    - name: Validate vm_count
      fail:
        msg: "vm_count must be positive"
      when: vm_count < 1

    - name: Convert comma-separated roles into list
      set_fact:
        parsed_roles: "{{ node_roles.split(',') }}"

    - name: Ensure role count matches VM count
      assert:
        that:
          - parsed_roles | length == vm_count

    - name: Generate VM numbers
      set_fact:
        vm_list: "{{ query('sequence','start=1 end=' + vm_count|string) }}"

    - name: Build VM → role map
      set_fact:
        vm_role_map: "{{ vm_list | zip(parsed_roles) | list }}"

    - debug:
        msg: "VM {{ vm_name_prefix }}-{{ item.0 }} will be {{ item.1 }}"
      loop: "{{ vm_role_map }}"

    - name: Get Rancher cluster info
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_info

    - name: Fail if cluster not found
      fail:
        msg: "Cluster {{ cluster_name }} not found in Rancher!"
      when: cluster_info.json.data | length == 0

    - name: Set cluster ID
      set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Create registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
        status_code: 201
      register: token_create

    - name: Wait for nodeCommand
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: reg_info
      until: reg_info.json.data[0].nodeCommand is defined and reg_info.json.data[0].nodeCommand != ""
      retries: 20
      delay: 5

    - name: Store registration data
      set_fact:
        node_command: "{{ reg_info.json.data[0].nodeCommand }}"
        registration_token: "{{ reg_info.json.data[0].token }}"

    - name: Create cloud-init files
      copy:
        dest: "/tmp/cloud-init-{{ vm_name_prefix }}-{{ item.0 }}.yml"
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl
            - docker.io

          write_files:
            - path: /etc/hosts
              content: |
                10.1.77.17 k8smanager.comtegra.pl
              owner: root:root
              permissions: '0644'

          runcmd:
            - systemctl enable docker
            - systemctl start docker
            - sleep 5
            - curl --insecure -I {{ rancher_url }}
            - |
              BASE="{{ node_command }}"
              FINAL=$(echo "$BASE" | sed 's/curl /curl --insecure /g')
              {% if 'etcd' in item.1 %}FINAL="$FINAL --etcd"{% endif %}
              {% if 'controlplane' in item.1 %}FINAL="$FINAL --controlplane"{% endif %}
              {% if 'worker' in item.1 %}FINAL="$FINAL --worker"{% endif %}
              FINAL="$FINAL --node-name {{ vm_name_prefix }}-{{ item.0 }}"
              echo "$FINAL" > /root/rancher-final.sh
              chmod +x /root/rancher-final.sh
            - bash /root/rancher-final.sh
      loop: "{{ vm_role_map }}"

    - name: Create VM on OpenStack
      openstack.cloud.server:
        state: present
        name: "{{ vm_name_prefix }}-{{ item.0 }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ lookup('file', '/tmp/cloud-init-' + vm_name_prefix + '-' + item.0|string + '.yml') }}"
        auto_ip: yes
        wait: yes
        timeout: 600
        validate_certs: false
      environment:
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_PROJECT_ID: "{{ os_project_id }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_INTERFACE: "{{ os_interface }}"
        OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
      register: new_vms
      loop: "{{ vm_role_map }}"

    - name: Show VM IPs
      debug:
        msg: "VM {{ vm_name_prefix }}-{{ item.0 }} → IP: {{
          new_vms.results[item.0 | int - 1].server.public_v4 |
          default(new_vms.results[item.0 | int - 1].server.private_v4)
        }}"
      loop: "{{ vm_role_map }}"

    - name: Cleanup cloud-init files
      file:
        path: "/tmp/cloud-init-{{ vm_name_prefix }}-{{ item.0 }}.yml"
        state: absent
      loop: "{{ vm_role_map }}"
